


			#cartManager


#Installazione del sistema operativo e ambiente di esecuzione della nostra immagine dal Docker Hub
FROM openjdk:17-alpine



ENV HISTORY_MANAGER_URL = http://localhost:8084/historyManager/processOrder