
  
x-common-variables: &common-variables
   MYSQL_DB_URL : jdbc:mysql://mysql-db-myamazon-container:3306/myamazon
   EUREKA_CLIENT_URL : http://eureka-container:8761/eureka

services:

 eureka-server:
  build: /eureka-server/
  image: eureka-image:0.0.1
  container_name: eureka-container
  ports:
  - 8761:8761
  
 gateway:
  build: /gateway/
  image: gateway-image:0.0.1
  container_name: gateway-container
  ports:
  - 8081:8081
  
 mysql-db:
  image: mysql:latest
  container_name: mysql-db-myamazon-container
  environment:
   MYSQL_DATABASE: myamazon
   MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  ports:
  - 3310:3306
  volumes:
  - mysqldb_data:/var/lib/mysql
  
 mongo-db:
    image: mongo:latest
    container_name: mongo-db-myamazon-container
    environment:
      MONGO_INITDB_DATABASE: history
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
      
 cart-manager-service:
  build: /cartManager/
  image: cart-manager-image:0.0.1
  container_name: cart-manager-container
  ports:
  - 8084:8084
  depends_on:
  - eureka-server
  - mysql-db
  restart: on-failure
  environment:
       <<: *common-variables  
     
 history-manager-service:
  build: /historyManager/
  image: history-manager-image:0.0.1
  container_name: history-manager-container
  ports:
  - 8085:8085
  depends_on:
  - eureka-server
  - mongo-db
  restart: on-failure
  environment:
       <<: *common-variables   
    
 product-manager-service:
  build: /productManager/
  image: product-manager-image:0.0.1
  container_name: product-manager-container
  ports:
  - 8083:8083
  depends_on:
  - eureka-server
  - mysql-db
  restart: on-failure
  environment:
       <<: *common-variables    
    
 user-manager-service:
  build: /userManager/
  image: user-manager-image:0.0.1
  container_name: user-manager-container
  ports:
  - 8082:8082
  depends_on:
  - eureka-server
  - mysql-db
  restart: on-failure
  environment:
       <<: *common-variables    
    

   
volumes:
  mongodb_data:
  mysqldb_data: