services:

 eureka-server:
  build: /eureka-server/
  image: eureka-image:0.0.1
  container_name: eureka-container
  ports:
  - 8761:8761
  
 gateway:
  build: /gateway-dbms/
  image: gateway-dbms-image:0.0.1
  container_name: gateway-dbms-container
  ports:
  - 8081:8081
  
 mysql-db:
  image: mysql:latest
  container_name: mysql-db-container
  environment:
   MYSQL_DATABASE: ultimo
   MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  ports:
  - 3309:3306
  volumes:
  - mysqldb_data:/var/lib/mysql
  
 mongo-db:
    image: mongo:latest
    container_name: mongo-db-container
    environment:
      MONGO_INITDB_DATABASE: ultimo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      
 sql-cruder-service:
  build: /sql-cruder/
  image: sql-cruder-image:0.0.1
  container_name: sql-cruder-container
  ports:
  - 8082:8082
  depends_on:
  - eureka-server
  - mysql-db
  restart: on-failure   
     
 nosql-cruder-service:
  build: /nosql-cruder/
  image: nosql-cruder-image:0.0.1
  container_name: nosql-cruder-container
  ports:
  - 8083:8083
  depends_on:
  - eureka-server
  - mongo-db
  restart: on-failure
  
  
  
  
  
volumes:
  mongodb_data:
  mysqldb_data: